In [10]:
import pandas as pd
import numpy as np

In [11]:
# create DataFrame
data = [
    {"Name": "Alex", "Age": 24, 'City': 'Paris'},
    {"Name": "Bob", "Age": 26, 'City': 'Geneva'},
    {"Name": "Charles", "Age": 24, 'City': 'Toronto'},
    {"Name": "Dia", "Age": 25, 'City': 'Auckland'}      
]

df = pd.DataFrame(data)

print(df)

      Name  Age      City
0     Alex   24     Paris
1      Bob   26    Geneva
2  Charles   24   Toronto
3      Dia   25  Auckland

In [12]:
# adding a hobby column
df['Hobby'] = ['Reading', 'Sports', 'Swimming', 'Meditation']
df

      Name  Age      City       Hobby
0     Alex   24     Paris     Reading
1      Bob   26    Geneva      Sports
2  Charles   24   Toronto    Swimming
3      Dia   25  Auckland  Meditation

In [13]:
# remove the column
df.drop('Age')

KeyError: "['Age'] not found in axis"

In [14]:
# default it will check for rows that is axis = 0
# as we have to check in column we will use axis = 1
df.drop('Age', axis=1)

      Name      City       Hobby
0     Alex     Paris     Reading
1      Bob    Geneva      Sports
2  Charles   Toronto    Swimming
3      Dia  Auckland  Meditation

In [15]:
df.columns

Index(['Name', 'Age', 'City', 'Hobby'], dtype='str')

In [18]:
# as we can see the changes are not permannet so we have two ways
# 1. store in another data frame
# 2. use inplace=True
df.drop('Hobby', axis=1, inplace=True)

In [20]:
df.columns  # now hobby is completely removed

Index(['Name', 'Age', 'City'], dtype='str')

In [21]:
df

      Name  Age      City
0     Alex   24     Paris
1      Bob   26    Geneva
2  Charles   24   Toronto
3      Dia   25  Auckland

In [22]:
## adding '1' to age column
df['Age'] = df.Age + 1
df

      Name  Age      City
0     Alex   25     Paris
1      Bob   27    Geneva
2  Charles   25   Toronto
3      Dia   26  Auckland

In [24]:
# get tge statistical summary of numerical columns
df.describe().T

     count   mean       std   min   25%   50%    75%   max
Age    4.0  25.75  0.957427  25.0  25.0  25.5  26.25  27.0

In [25]:
# reading the data from csv file
df = pd.read_csv('sales_data.csv', encoding_errors='ignore')

df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [26]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
ORDERNUMBER,2823.0,10258.725115,92.085478,10100.00,10180.00,10262.0,10333.5,10425.0
QUANTITYORDERED,2823.0,35.092809,9.741443,6.00,27.00,35.0,43.0,97.0
PRICEEACH,2823.0,83.658544,20.174277,26.88,68.86,95.7,100.0,100.0
ORDERLINENUMBER,2823.0,6.466171,4.225841,1.00,3.00,6.0,9.0,18.0
SALES,2823.0,3553.889072,1841.865106,482.13,2203.43,3184.8,4508.0,14082.8
QTR_ID,2823.0,2.717676,1.203878,1.00,2.00,3.0,4.0,4.0
MONTH_ID,2823.0,7.092455,3.656633,1.00,4.00,8.0,11.0,12.0
YEAR_ID,2823.0,2003.815090,0.699670,2003.00,2003.00,2004.0,2004.0,2005.0
MSRP,2823.0,100.715551,40.187912,33.00,68.00,99.0,124.0,214.0

In [27]:
df.dtypes

ORDERNUMBER           int64
QUANTITYORDERED       int64
PRICEEACH           float64
ORDERLINENUMBER       int64
SALES               float64
ORDERDATE               str
STATUS                  str
QTR_ID                int64
MONTH_ID              int64
YEAR_ID               int64
PRODUCTLINE             str
MSRP                  int64
PRODUCTCODE             str
CUSTOMERNAME            str
PHONE                   str
ADDRESSLINE1            str
ADDRESSLINE2            str
CITY                    str
STATE                   str
POSTALCODE              str
COUNTRY                 str
TERRITORY               str
CONTACTLASTNAME         str
CONTACTFIRSTNAME        str
DEALSIZE                str
dtype: object

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDERNUMBER       2823 non-null   int64
 1   QUANTITYORDERED   2823 non-null   int64
 2   PRICEEACH         2823 non-null   float64
 3   ORDERLINENUMBER   2823 non-null   int64
 4   SALES             2823 non-null   float64
 5   ORDERDATE         2823 non-null   str
 6   STATUS            2823 non-null   str
 7   QTR_ID            2823 non-null   int64
 8   MONTH_ID          2823 non-null   int64
 9   YEAR_ID           2823 non-null   int64
 10  PRODUCTLINE       2823 non-null   str
 11  MSRP              2823 non-null   int64
 12  PRODUCTCODE       2823 non-null   str
 13  CUSTOMERNAME      2823 non-null   str
 14  PHONE             2823 non-null   str
 15  ADDRESSLINE1      2823 non-null   str
 16  ADDRESSLINE2      302 non-null    str
 17  CITY              2823 non-null   str
 18  STATE             1337 non-null   str
 19  POSTALCODE        2747 non-null   str
 20  COUNTRY           2823 non-null   str
 21  TERRITORY         1749 non-null   str
 22  CONTACTLASTNAME   2823 non-null   str
 23  CONTACTFIRSTNAME  2823 non-null   str
 24  DEALSIZE          2823 non-null   str
dtypes: float64(2), int64(7), str(16)
memory usage: 551.5 KB

In [32]:
## Handling missing values
df.isna().sum()

ORDERNUMBER            0
QUANTITYORDERED        0
PRICEEACH              0
ORDERLINENUMBER        0
SALES                  0
ORDERDATE              0
STATUS                 0
QTR_ID                 0
MONTH_ID               0
YEAR_ID                0
PRODUCTLINE            0
MSRP                   0
PRODUCTCODE            0
CUSTOMERNAME           0
PHONE                  0
ADDRESSLINE1           0
ADDRESSLINE2        2521
CITY                   0
STATE               1486
POSTALCODE            76
COUNTRY                0
TERRITORY           1074
CONTACTLASTNAME        0
CONTACTFIRSTNAME       0
DEALSIZE               0
dtype: int64

In [35]:
df.isna().any()

ORDERNUMBER         False
QUANTITYORDERED     False
PRICEEACH           False
ORDERLINENUMBER     False
SALES               False
ORDERDATE           False
STATUS              False
QTR_ID              False
MONTH_ID            False
YEAR_ID             False
PRODUCTLINE         False
MSRP                False
PRODUCTCODE         False
CUSTOMERNAME        False
PHONE               False
ADDRESSLINE1        False
ADDRESSLINE2         True
CITY                False
STATE                True
POSTALCODE           True
COUNTRY             False
TERRITORY            True
CONTACTLASTNAME     False
CONTACTFIRSTNAME    False
DEALSIZE            False
dtype: bool

In [37]:
# filling missing values with default values
df_filled = df.fillna(0)
df_filled.isna().sum()

ORDERNUMBER         0
QUANTITYORDERED     0
PRICEEACH           0
ORDERLINENUMBER     0
SALES               0
ORDERDATE           0
STATUS              0
QTR_ID              0
MONTH_ID            0
YEAR_ID             0
PRODUCTLINE         0
MSRP                0
PRODUCTCODE         0
CUSTOMERNAME        0
PHONE               0
ADDRESSLINE1        0
ADDRESSLINE2        0
CITY                0
STATE               0
POSTALCODE          0
COUNTRY             0
TERRITORY           0
CONTACTLASTNAME     0
CONTACTFIRSTNAME    0
DEALSIZE            0
dtype: int64

In [44]:
# filling missing val with the mean or median of that column, if data is "Numerical"
# for categorical data 'mode' could be the better option 
# we also have one more option 'most frequesnt' but we dp that with Pipeline and ColumnTransformer
df['City_filled'] = df.CITY.fillna(df.CITY.mode())
df.CITY.mode()

0    Madrid
Name: CITY, dtype: str

In [45]:
df.dtypes

ORDERNUMBER           int64
QUANTITYORDERED       int64
PRICEEACH           float64
ORDERLINENUMBER       int64
SALES               float64
ORDERDATE               str
STATUS                  str
QTR_ID                int64
MONTH_ID              int64
YEAR_ID               int64
PRODUCTLINE             str
MSRP                  int64
PRODUCTCODE             str
CUSTOMERNAME            str
PHONE                   str
ADDRESSLINE1            str
ADDRESSLINE2            str
CITY                    str
STATE                   str
POSTALCODE              str
COUNTRY                 str
TERRITORY               str
CONTACTLASTNAME         str
CONTACTFIRSTNAME        str
DEALSIZE                str
City_filled             str
dtype: object

In [47]:
# renaming columns
df = df.rename(columns={'SALES':'Total_Sales'})  # we can pass multiple columns
df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,Total_Sales,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,City_filled
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small,NYC
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small,Reims
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium,Paris
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium,Pasadena
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium,San Francisco

In [50]:
# change data types
df['new_values'] = df.Total_Sales.astype(int)
df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,Total_Sales,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,City_filled,new_values
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,NYC,NY,10022,USA,NaN,Yu,Kwai,Small,NYC,2871
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small,Reims,2765
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium,Paris,3884
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium,Pasadena,3746
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium,San Francisco,5205

In [54]:
df['new_quantity'] = df.QUANTITYORDERED.apply(lambda x: x*2)
df[['QUANTITYORDERED', 'new_quantity']].head()

   QUANTITYORDERED  new_quantity
0               30            60
1               34            68
2               41            82
3               45            90
4               49            98

In [55]:
# Data Agrregating and grouping
df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,Total_Sales,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,City_filled,new_values,new_quantity
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,NY,10022,USA,NaN,Yu,Kwai,Small,NYC,2871,60
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,NaN,51100,France,EMEA,Henriot,Paul,Small,Reims,2765,68
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium,Paris,3884,82
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,CA,90003,USA,NaN,Young,Julie,Medium,Pasadena,3746,90
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,CA,NaN,USA,NaN,Brown,Julie,Medium,San Francisco,5205,98

In [58]:
pd.unique(df['CITY'])

<StringArray>
[           'NYC',          'Reims',          'Paris',       'Pasadena',
  'San Francisco',     'Burlingame',          'Lille',         'Bergen',
      'Melbourne',         'Newark',    'Bridgewater',         'Nantes',
      'Cambridge',       'Helsinki',        'Stavern',      'Allentown',
       'Salzburg',      'Chatswood',    'New Bedford',      'Liverpool',
         'Madrid',           'Lule',      'Singapore', 'South Brisbane',
   'Philadelphia',           'Lyon',      'Vancouver',        'Burbank',
      'New Haven',      'Minato-ku',         'Torino',          'Boras',
     'Versailles',     'San Rafael',         'Nashua',     'Brickhaven',
   'North Sydney',       'Montreal',          'Osaka',   'White Plains',
      'Kobenhavn',         'London',       'Toulouse',      'Barcelona',
    'Los Angeles',      'San Diego',      'Bruxelles',      'Tsawassen',
         'Boston',          'Cowes',           'Oulu',       'San Jose',
           'Graz',    'Makati City',      'Marseille',           'Koln',
         'Gensve',  'Reggio Emilia',      'Frankfurt',          'Espoo',
         'Dublin',     'Manchester',        'Aaarhus',       'Glendale',
        'Sevilla',       'Brisbane',     'Strasbourg',      'Las Vegas',
           'Oslo',        'Bergamo',   'Glen Waverly',         'Munich',
      'Charleroi']
Length: 73, dtype: str

In [61]:
# mean of totalsales by city
mean_by_city = df.groupby('CITY')['Total_Sales'].mean()
mean_by_city.head(), len(mean_by_city)

(CITY
 Aaarhus      3725.761111
 Allentown    3939.940000
 Barcelona    3409.211304
 Bergamo      2874.077500
 Bergen       3849.664828
 Name: Total_Sales, dtype: float64,
 73)

In [62]:
grouped_sum = df.groupby(['CITY', 'STATUS'])['Total_Sales'].sum()
grouped_sum

CITY          STATUS
Aaarhus       Shipped       100595.55
Allentown     In Process      6166.80
              Shipped       115971.34
Barcelona     Shipped        78411.86
Bergamo       Shipped       137955.72
                              ...
Toulouse      Shipped        70488.44
Tsawassen     Shipped        74634.85
Vancouver     Shipped        75238.92
Versailles    Shipped        64834.32
White Plains  Shipped        85555.99
Name: Total_Sales, Length: 94, dtype: float64

In [65]:
# applying multiple aggregate function
agg_groupby = df.groupby('CITY')['Total_Sales'].agg(['mean', 'sum', 'count'])
agg_groupby.head()

                  mean        sum  count
CITY
Aaarhus    3725.761111  100595.55     27
Allentown  3939.940000  122138.14     31
Barcelona  3409.211304   78411.86     23
Bergamo    2874.077500  137955.72     48
Bergen     3849.664828  111640.28     29

In [74]:
## Merging and joining dataframes
df1 = pd.DataFrame(
    {'Keys': ['A', 'B', 'C'],
     'Value1': [1, 2, 3]}
)

df2 = pd.DataFrame(
    {'Keys': ['A', 'B', 'D'],
     'Value2': [4, 4, 6]}
)

In [75]:
df1

  Keys  Value1
0    A       1
1    B       2
2    C       3

In [76]:
df2

  Keys  Value2
0    A       4
1    B       4
2    D       6

In [77]:
df1.merge(df2)

  Keys  Value1  Value2
0    A       1       4
1    B       2       4

In [79]:
# merging the dataframe on key column
pd.merge(df1, df2,
         on='Keys',
         how='inner')

  Keys  Value1  Value2
0    A       1       4
1    B       2       4

In [81]:
pd.merge(df1, df2,
         on='Keys',
         how='outer')

  Keys  Value1  Value2
0    A     1.0     4.0
1    B     2.0     4.0
2    C     3.0     NaN
3    D     NaN     6.0

In [82]:
pd.merge(df1, df2,
         on='Keys',
         how='left')

  Keys  Value1  Value2
0    A       1     4.0
1    B       2     4.0
2    C       3     NaN

In [83]:
pd.merge(df1, df2,
         on='Keys',
         how='right')

  Keys  Value1  Value2
0    A     1.0       4
1    B     2.0       4
2    D     NaN       6

In [88]:
# concatenating
# Pass df1 and df2 inside a list
pd.concat([df1, df2])

  Keys  Value1  Value2
0    A     1.0     NaN
1    B     2.0     NaN
2    C     3.0     NaN
0    A     NaN     4.0
1    B     NaN     4.0
2    D     NaN     6.0

In [89]:
pd.concat([df1, df2], ignore_index=True)

  Keys  Value1  Value2
0    A     1.0     NaN
1    B     2.0     NaN
2    C     3.0     NaN
3    A     NaN     4.0
4    B     NaN     4.0
5    D     NaN     6.0